# PlotTree.py  construction of PlotTree

import os
import argparse
import json
import torch
import numpy as np
from tqdm import tqdm
from pathlib import Path
import pandas as pd
import torch.nn.functional as F
from sentence_transformers import SentenceTransformer
import time

from kmeans_pytorch import kmeans # Please install the dependence according to the README file.
from utils.llm import get_llm, chat
os.environ['SENTENCE_TRANSFORMERS_HOME'] = "ckpt"


def load_json(json_path):
    with open(json_path, "r", encoding="utf-8") as file:
        json_str = file.read()
    data = json.loads(json_str)
    return data
    
def plot_similarity(points, centroid):
    """
    Calculate plot similarity distance between points and centroid.
    """
    points = points.to(torch.float32)
    centroid = centroid.to(torch.float32)
    points, points_ids = points[:, :-1], points[:, -1] 
    centroid, centroid_id = centroid[:-1], centroid[-1]

    points_normalized = F.normalize(points, dim=1)
    centroid_normalized = F.normalize(centroid.unsqueeze(0), dim=1)
    distance_ids = torch.abs(points_ids-centroid_id)

    return 1 - torch.mm(points_normalized, centroid_normalized.T).squeeze() + distance_ids

# ---  Defines the core algorithm functions of PlotTree ---
def get_embedding_from_text(text: str, model: SentenceTransformer) -> torch.Tensor:
    """
    Convert the text to RAG Embedding.
    Input:
        text (str): A single text string.
        model (SentenceTransformer): Preloaded RAG Embedding model.
    Output:
        torch.Tensor: The embedding vector (1D Tensor) corresponding to the text.
    """
    return model.encode([text], convert_to_tensor=True, device=model.device, prompt_name="query").squeeze(0)


chatbot = None
llm = None




def get_llm_summary(args, plot_descriptions_list: list[str], llm_model) -> str:
    """
    Call the LLM to summarize the plot description list.
    Input:
        plot_descriptions_list (list[str]): A list of subplot description strings that need to be summarized.
        llm_model: llm model you need
    Output:
        str: A coherent plot summary generated by LLM.
    """
    combined_input_text = " ".join(plot_descriptions_list)

    # Example Prompt (You will need to optimize it based on your LLM and tasks)
    prompt = (
        f"You are a master storyteller tasked with summarizing video content. "
        f"Given a sequence of plot descriptions from a video, your goal is to create a concise and coherent plot summary (or synopsis) "
        f"that captures the main narrative flow. "
        f"Focus on the the progression of events. "
        f"Organize the summary chronologically, highlighting major developments in the plot. "
        f"Keep the summary brief and in plain text, suitable for a plot overview. \n\n"
        f"Plot Descriptions: {combined_input_text}\n\n"
        f"Summary: -nothinking"
    )
    
    global chatbot, llm
    llm = get_llm(llm_model, args)
    print(f"Loading {llm_model} first Time.")
    summary = chat(llm, question=prompt)
        # print(f"{llm_model}: {summary}")
    if summary.startswith(prompt):
        summary = summary[len(prompt):].strip()
    # if len(summary) > 500: summary = summary[:500] + "..."
    return summary



def _decide_k_value(num_data_points: int, compression_factor: int = 4) -> int:
    """
    The K value (number of clusters) for the current level is determined based on the given compression factor hyperparameter.
    Args:
        num_data_points (int): Number of nodes in the current layer.
        compression_factor (int): Compression factor hyperparameter, for example 4 (meaning the number of nodes is compressed to 1/4 of the original).
    Returns:
        int: The calculated K value.
    """
    if num_data_points <= 1:
        return 1 
    if compression_factor < 2:
        compression_factor = 2 
    k_final = num_data_points // compression_factor
    if k_final < 1:
        k_final = 1
    if k_final > num_data_points:
        k_final = num_data_points 
    return k_final



def _post_process_clusters(
    cluster_ids_x: torch.Tensor,
    cluster_centers: torch.Tensor,
    current_nodes_embeddings: torch.Tensor,
    min_nodes_in_cluster: int,
    rag_embedding_model_device: torch.device
) -> tuple[torch.Tensor, torch.Tensor]:
    """
   Post-processing of clustering results involves identifying and merging "orphan clusters" (clusters containing too few child nodes).

    Args:
        cluster_ids_x (torch.Tensor): K-Means clustering results (cluster ID corresponding to each point).
        cluster_centers (torch.Tensor): K-Means cluster center.
        current_level_nodes (list[dict]): All node objects in the current layer (each node is a data point in K-Means).
        min_nodes_in_cluster (int): A cluster is considered an "orphan cluster" when it contains fewer than this number of child nodes.
        rag_embedding_model_device (torch.device): Devices used for tensor operations.

    Returns:
        tuple[torch.Tensor, torch.Tensor]:
            - refined_cluster_ids_x (torch.Tensor): The cluster ID corresponding to each point after processing.
            - refined_cluster_centers (torch.Tensor): The cluster center after processing.
    """
    tqdm.write("  -> Post-processing clusters to handle 'orphan' clusters based on node count...")

    original_num_clusters = len(cluster_centers)
    node_to_cluster_map = cluster_ids_x.tolist() 

    orphan_cluster_ids = set()
    cluster_to_nodes_map = {i: [] for i in range(original_num_clusters)}
    
    # 1. Identify orphan clusters (based on the number of child nodes)
    for node_idx, cluster_id in enumerate(node_to_cluster_map):
        cluster_to_nodes_map[cluster_id].append(node_idx)

    for cluster_id, node_indices_in_cluster in cluster_to_nodes_map.items():
        # If a cluster contains no nodes, or contains fewer than a threshold number of child nodes.
        if len(node_indices_in_cluster) < min_nodes_in_cluster:
            orphan_cluster_ids.add(cluster_id)
    
    tqdm.write(f"    Identified {len(orphan_cluster_ids)} orphan clusters out of {original_num_clusters}.")

    if not orphan_cluster_ids:
        return cluster_ids_x, cluster_centers

    # 2. Merging orphan clusters
    refined_cluster_ids_x = cluster_ids_x.clone() 
    
    non_orphan_cluster_centers = [
        cluster_centers[i] for i in range(original_num_clusters) if i not in orphan_cluster_ids
    ]
    
    if not non_orphan_cluster_centers: # All clusters are orphan clusters, and they are all merged into one.
        tqdm.write("    All clusters are orphans. Merging all into a single cluster (cluster ID 0).")
        refined_cluster_ids_x[:] = 0 
        refined_cluster_centers = current_nodes_embeddings.mean(dim=0).unsqueeze(0) # Recalculate the center of all points
        return refined_cluster_ids_x, refined_cluster_centers

    non_orphan_cluster_centers_tensor = torch.stack(non_orphan_cluster_centers).to(rag_embedding_model_device)

    # Reassign each node in the orphan cluster to the nearest non-orphan cluster.
    for orphan_cluster_id in orphan_cluster_ids:
        nodes_in_orphan_cluster = cluster_to_nodes_map[orphan_cluster_id]
        if not nodes_in_orphan_cluster: 
            continue

        for node_idx in nodes_in_orphan_cluster:
            node_embedding = current_nodes_embeddings[node_idx]
            
            distances_to_non_orphans = plot_similarity(non_orphan_cluster_centers_tensor, node_embedding)
            
            closest_non_orphan_local_idx = torch.argmin(distances_to_non_orphans).item()
            
            # Get the original ID of the nearest non-orphan cluster
            closest_non_orphan_global_id = [
                i for i in range(original_num_clusters) if i not in orphan_cluster_ids
            ][closest_non_orphan_local_idx]
            
            refined_cluster_ids_x[node_idx] = closest_non_orphan_global_id
    
    # 3.Recalculate the new cluster centers and cluster ID mappings 
    # (because some clusters may disappear, and cluster IDs need to be remapped).
    new_cluster_id_map = {} 
    next_new_cluster_id = 0
    
    # Collect and process the actual cluster IDs
    actual_new_cluster_ids = sorted(list(set(refined_cluster_ids_x.tolist())))
    for old_id in actual_new_cluster_ids:
        new_cluster_id_map[old_id] = next_new_cluster_id
        next_new_cluster_id += 1
    
    # Apply new ID mapping
    for node_idx in range(len(refined_cluster_ids_x)):
        old_id = refined_cluster_ids_x[node_idx].item()
        refined_cluster_ids_x[node_idx] = new_cluster_id_map[old_id]
    
    num_refined_clusters = next_new_cluster_id # Final number of clusters
    refined_cluster_centers = torch.zeros(num_refined_clusters, cluster_centers.shape[1], device=rag_embedding_model_device)
    counts = torch.zeros(num_refined_clusters, device=rag_embedding_model_device)
    
    for node_idx in range(len(current_nodes_embeddings)):
        new_id = refined_cluster_ids_x[node_idx].item()
        refined_cluster_centers[new_id] += current_nodes_embeddings[node_idx]
        counts[new_id] += 1
        
    # To prevent division by zero, for potentially still existing empty clusters (theoretically not, but for safety reasons).
    counts[counts == 0] = 1 
    refined_cluster_centers = refined_cluster_centers / counts.unsqueeze(1)
    
    tqdm.write(f"    Clusters refined from {original_num_clusters} to {num_refined_clusters}.")

    return refined_cluster_ids_x, refined_cluster_centers


def temporal_decay(l, alpha=1.0, epsilon=1e-2):
    """
    Calculate the temporal decay coefficient for hierarchical clustering.
    
    Parameters:
    l (int): Hierarchy level (deeper level has larger l value)
    alpha (float): Scaling factor controlling the decay rate (default: 1.0)
    epsilon (float): Small constant to prevent division by zero (default: 1e-2)
    
    Returns:
    float: Decay coefficient lambda(l)
    """
    return 1.0 / (alpha * l + epsilon)


# --- Main PlotTree construction function ---
def build_plottree_for_episode(args, captions_json_path: Path, episode_id: str, 
                           rag_embedding_model: SentenceTransformer, llm_model,
                           output_dir: Path,
                           compression_factor: int = 4,
                           min_nodes_in_cluster: int = 2,
                           temporal_weight_rate: float = 100) -> Path:
    """
    Main function: The core logic for building a narrative summary tree (PlotTree) for the video from the bottom up.
    
    Input:
        captions_json_path (Path): The path to a JSON file containing the captions for all video frames.
                                   The structure is: {"episode_id": [{"caption":..., "subtitle":..., "charcters_info":...}, ...]}
        episode_id (str): The current episode ID being processed
        rag_embedding_model (SentenceTransformer): A model for generating plot embeddings.
        llm_model: The name of the local LLM model used to generate plot summaries.
        output_dir (Path): The directory where the JSON results are stored.
        min_cluster_size (int): The minimum number of frames per cluster during clustering is also one of the conditions for stopping the recursion.
        max_k_per_level (int): The maximum K value for each cluster level.
    
    输出:
        Path: The path to the JSON file containing the list of PlotTree nodes.
    """
    # 0. Parameter verification and environment preparation
    if not captions_json_path.exists():
        raise FileNotFoundError(f"Captions JSON not found at {captions_json_path}")
    output_dir.mkdir(parents=True, exist_ok=True) # 确保输出目录存在

    # 1. Read raw data
    with open(captions_json_path, 'r', encoding='utf-8') as f:
        full_captions_data = json.load(f)
    
    # Assuming the JSON contains only one episode's data, or you need to iterate through all episodes
    # Here we only process the first episode (e.g., "Friends-S01E01")
    frames_data = full_captions_data[episode_id]

    all_nodes_in_tree = [] # Store all nodes and ultimately save to JSON.
    node_id_counter = 0    # Used to generate unique node IDs
    
    # 2. Initialization: Create the leaf node level (Level 0)
    # current_level_nodes: A list that stores the node objects at the current level.
    # frame_narrative_embeddings_map: A dictionary is used to quickly find the plot embedding corresponding to the original frame ID.
    tqdm.write(f"--- Processing Episode: {episode_id} ---")
    tqdm.write("2.1 Creating Leaf Nodes (Level 0)...")
    
    current_level_nodes = []
    frame_narrative_embeddings_map = {} 
    total_frames = len(frames_data)

    output_filepath = output_dir / f"{episode_id}.json"



    all_nodes_in_tree = []
    
    for i, frame_data in tqdm(enumerate(frames_data), total=len(frames_data), desc="Encoding Leaf Nodes"):
        # Convert the raw frame data into a unified text description.
        # format: {"caption":..., "subtitle":..., "face_bbox":..., "charcters_info":...}
        # Ensure that characters_info is processed as a string.
        char_str = ", ".join(frame_data['charcters_info']) if isinstance(frame_data.get('charcters_info'), list) else frame_data.get('charcters_info', '')
        combined_text = (
                f"Visual description: {frame_data.get('caption', '')} "
        )
        sub = frame_data.get('subtitle', '')
        char = char_str
        if sub:
            combined_text += f"Spoken dialogue: {frame_data.get('subtitle', '')} "
        if char:
            combined_text += f"Characters: {char_str}."
        # Get plot embedding
        narrative_embedding = get_embedding_from_text(combined_text, rag_embedding_model)
        # Normalized Frame Index
        temporal_weight = temporal_decay(l=0, alpha=temporal_weight_rate)
        normalized_time = torch.tensor([float(i) / total_frames], device=rag_embedding_model.device, dtype=torch.float32)

        
        narrative_embedding = torch.cat((narrative_embedding, temporal_weight * normalized_time), dim=0)
        # Storing the mapping from the original frame ID to the embedded frame ID.
        frame_narrative_embeddings_map[i] = narrative_embedding
        
        # Create leaf node objects
        original_plot_description = combined_text
        node_id = f"leaf_{i}"
        leaf_node = {
                "node_id": node_id,
                "parent_id": None, 
                "level": 0,        
                "start_frame_idx": i,
                "end_frame_idx": i,
                "original_frame_indices": [i],
                "plot_summary": original_plot_description, # Original description as a summary
                "plot_embedding": narrative_embedding.tolist(), # Converting to a list facilitates JSON serialization.
                "children_node_ids": [] 
        }
        current_level_nodes.append(leaf_node)
        all_nodes_in_tree.append(leaf_node) # 添加到所有节点列表
            
             
    tqdm.write(f"Leaf nodes created. Total: {len(current_level_nodes)}")

    # 3. Iterative aggregation loop (bottom-up tree construction)
    current_level = 0
    while len(current_level_nodes) > 1: # As long as there is more than one node, continue aggregation.
        current_level += 1
        tqdm.write(f"\n3.1 Aggregating Level {current_level-1} to Level {current_level}...")
        
        next_level_nodes = [] # Store the newly created parent node

        # Prepare the embeddings of all nodes in the current layer for K-Means clustering.
        current_nodes_embeddings = torch.stack([torch.tensor(node["plot_embedding"], device=rag_embedding_model.device) for node in current_level_nodes])
        
        # Intelligently determines the K value for the current level
        # K-Means clustering (requires ensuring the kmeans function is imported)
        k = _decide_k_value(
            num_data_points=current_nodes_embeddings.shape[0], 
            compression_factor=compression_factor
        )
        tqdm.write(f"Decided K for Level {current_level}: {k}")

        if k <= 1: # The next step is single root node, direct aggregation.
            tqdm.write("Reached single root node. Stopping aggregation.")
            break
        elif k <= 0:# Stop if the value of K is unreasonable.
             tqdm.write("Decided K is too small or zero. Stopping aggregation.")
             break
        current_nodes_embeddings.to(torch.device("cpu"))
        rag_embedding_model.to(torch.device("cpu"))
        # Perform K-Means clustering (cluster the embeddings of nodes in the current layer)
        # from kmeans_pytorch import kmeans
        print("Using plot Distance")
        cluster_ids_x, cluster_centers = kmeans(
            X=current_nodes_embeddings, 
            num_clusters=k, 
            distance='plot', #'cosine' if current_level != 1 else 'plot', 
            device=rag_embedding_model.device # Ensure it runs on the correct device
        )
        
        current_nodes_embeddings.to(torch.device(torch.device("cuda" if torch.cuda.is_available() else "cpu")))
        rag_embedding_model.to(torch.device("cuda" if torch.cuda.is_available() else "cpu"))

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        # Pass in min_nodes_in_cluster to handle orphan clusters.
        cluster_ids_x, cluster_centers = _post_process_clusters(
            cluster_ids_x, 
            cluster_centers, 
            current_nodes_embeddings, # Pass in the embeddings of the current layer node (as the raw data points for KMeans).
            min_nodes_in_cluster, # Pass in the minimum number of child nodes threshold
            rag_embedding_model.device
        )
        # Re-determine the actual K value after processing
        k = len(cluster_centers)
        # If K becomes 0 after post-processing (all clusters have been merged into one, but may not have been created correctly), 
        # special handling is required.
        if k == 0:
            tqdm.write("    Post-processing resulted in 0 clusters. Stopping aggregation.")
            break 
        tqdm.write(f"  K after post-processing: {k}.")

        
        # Iterate through each cluster and create a new parent node.
        for cluster_id in tqdm(range(k), desc=f"3.2 Creating Level {current_level} Nodes"):
            indices_in_current_level_cluster = torch.where(cluster_ids_x == cluster_id)[0]
            if indices_in_current_level_cluster.numel() == 0:
                continue 

            # Get child nodes (from the current layer)
            children_nodes_current_level = [current_level_nodes[idx.item()] for idx in indices_in_current_level_cluster]
            
            # Aggregate all original frame indices (for the new parent node).
            aggregated_original_frame_indices = sorted(list(
                set(idx for node in children_nodes_current_level for idx in node["original_frame_indices"])
            ))
            # represent_id = sum(aggregated_original_frame_indices)/len(aggregated_original_frame_indices)
            represent_id = min(aggregated_original_frame_indices)
            normalized_time = torch.tensor([ represent_id/ (total_frames - 1)], device=rag_embedding_model.device, dtype=torch.float32)
            temporal_weight = temporal_decay(l=current_level, alpha=temporal_weight_rate)
            # LLM summary: Aggregates subplots to generate a summary of the parent plot.
            plot_descriptions_to_summarize = [node["plot_summary"] for node in children_nodes_current_level]
            summary_text = get_llm_summary(args, plot_descriptions_to_summarize, llm_model)

            parent_node_plot_embedding = get_embedding_from_text(summary_text, rag_embedding_model) 
            parent_node_plot_embedding = torch.cat((parent_node_plot_embedding, temporal_weight * normalized_time), dim=0)
            # Create a new parent node object
            parent_node_id = f"level_{current_level}_cluster_{cluster_id}"
            parent_node = {
                "node_id": parent_node_id,
                "parent_id": None, # For now, set it to None; update it in the child nodes.
                "level": current_level,
                "start_frame_idx": aggregated_original_frame_indices[0],
                "end_frame_idx": aggregated_original_frame_indices[-1],
                "original_frame_indices": aggregated_original_frame_indices,
                "plot_summary": summary_text,
                "plot_embedding": parent_node_plot_embedding.tolist(), # Converting to a list facilitates JSON serialization.
                "children_node_ids": [node["node_id"] for node in children_nodes_current_level]
            }
            next_level_nodes.append(parent_node)
            all_nodes_in_tree.append(parent_node) 
            print([node["node_id"] for node in children_nodes_current_level])
            # Update the parent_id of child nodes (to ensure that parent-child relationships are established in the tree).
            for child_node in children_nodes_current_level:
                # Find the child nodes in all_nodes_in_tree and update their parent_id.
                for node_in_all in all_nodes_in_tree:
                    if node_in_all["node_id"] == child_node["node_id"]:
                        node_in_all["parent_id"] = parent_node_id
                        break
        
        current_level_nodes = next_level_nodes # Enter the next cycle
        tqdm.write(f"Level {current_level} created. Total nodes at this level: {len(current_level_nodes)}")

    # 4. Root node processing (after the loop ends, ensure there is a clearly defined root node).
    if len(current_level_nodes) == 1:
        root_node = current_level_nodes[0]
        root_node["parent_id"] = None 
        tqdm.write(f"PlotTree construction complete. Root node ID: {root_node['node_id']}")
    else:
        # If the loop terminates prematurely and there are multiple top-level nodes, a virtual root node is created.
        tqdm.write("PlotTree construction ended with multiple top-level nodes, creating a dummy root.")
        final_root_id = "root_summary"
        final_root_original_frames = sorted(list(set(idx for node in current_level_nodes for idx in node["original_frame_indices"])))
        final_root_summary = get_llm_summary(args, [node["plot_summary"] for node in current_level_nodes], llm_model)
        final_root_embedding = get_embedding_from_text(final_root_summary, rag_embedding_model) 
        
        final_root_node = {
            "node_id": final_root_id,
            "parent_id": None,
            "level": current_level,
            "start_frame_idx": final_root_original_frames[0],
            "end_frame_idx": final_root_original_frames[-1],
            "original_frame_indices": final_root_original_frames,
            "plot_summary": final_root_summary,
            "plot_embedding": final_root_embedding.tolist(),
            "children_node_ids": [node["node_id"] for node in current_level_nodes]
        }
        all_nodes_in_tree.append(final_root_node)

        # Update the parent IDs of these top-level nodes to point to the newly created virtual root node.
        for node_in_all in all_nodes_in_tree:
            if node_in_all["node_id"] in [n["node_id"] for n in current_level_nodes]:
                node_in_all["parent_id"] = final_root_id


    # 5. Save results
    output_filepath = output_dir / f"{episode_id}.json"
    for index, node in enumerate(all_nodes_in_tree):
        del all_nodes_in_tree[index]["plot_embedding"]
        
    with open(output_filepath, 'w', encoding='utf-8') as f:
        json.dump(all_nodes_in_tree, f, indent=4)
    
    tqdm.write(f"PlotTree nodes saved to: {output_filepath}")
    return output_filepath, len(frames_data)


def main():
    arg_parser = argparse.ArgumentParser()
    # primary setting
    arg_parser.add_argument("--captions_path", type=str, default="data/captions/Friends.json")
    arg_parser.add_argument('--output_base_dir', type=str, default="results/PlotTree", help="Base directory where PlotTree JSONs are stored.")  
    arg_parser.add_argument('--llm_model', type=str, default="Gemini-2.0-flash")
    arg_parser.add_argument("--openai_model", default="gemini-2.0-flash",type=str, help="model name of GPT")
    arg_parser.add_argument("--openai_key", required=True, type=str, help="key for llm")
    arg_parser.add_argument("--openai_proxy", required=True, type=str, help="proxy for llm")
    arg_parser.add_argument('--compression_factor', type=int, default=12)
    arg_parser.add_argument('--temporal_weight', type=float, default=100)
    arg_parser.add_argument('--min_nodes_in_cluster', type=int, default=2)
    args = arg_parser.parse_args()

    # Make sure the directory exists !!!
    args.captions_path = Path(args.captions_path)
    args.output_base_dir = Path(f"results/PlotTree/{args.llm_model}_{args.compression_factor}_{args.temporal_weight}")
    print(args.output_base_dir )
    args.output_base_dir.mkdir(parents=True, exist_ok=True)

    tqdm.write("Loading RAG Embedding Model...")
    rag_embedding_model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    rag_embedding_model.to(device)

    
    tqdm.write("RAG Embedding Model Loaded.")
    print("Loading", args.captions_path , "...")
    # 1. loading raw caption data
    with open(args.captions_path, 'r', encoding='utf-8') as f:
        full_captions_data = json.load(f)
    keys = full_captions_data.keys()
    
    for episode_id in list(keys)[:]:
        output_filepath = args.output_base_dir / f"{episode_id}.json"
        
        if output_filepath.exists():
            print(output_filepath, 'Existing!!!')
            continue
        tqdm.write(f"Building PlotTree for the episode... for {episode_id}")
        plottree_json_path, caption_size = build_plottree_for_episode(
            args = args,
            captions_json_path=args.captions_path,
            episode_id = episode_id,
            rag_embedding_model=rag_embedding_model,
            llm_model=args.llm_model, 
            output_dir=args.output_base_dir,
            compression_factor = args.compression_factor,
            min_nodes_in_cluster=args.min_nodes_in_cluster,
            temporal_weight_rate=args.temporal_weight
        )
        tqdm.write(f"PlotTree construction finished. Tree saved to: {plottree_json_path}")
        

if __name__ == '__main__':
    main()